### ISSUE TITLE
hi yash this code isn't working , i have forked your repository after gettting errors in my code.

### ISSUE THREAD

**Issue by dereksheperd89** [theyashpatel/yt-react-weather-app#2]

**Comment by dereksheperd89** [comment]
this is the error message weatherService.js:49 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slice')
    at formatForecastWeather (weatherService.js:49:1)
    at async getFormattedWeatherData (weatherService.js:76:1)
    at async fetchWeather (App.js:23:1)

**Comment by Vaibhav2887** [comment]
whats its solution

**Comment by priyank-1** [comment]
Actually the url fetched doesn't provide daily and hourly responses and the timezone offset requires a bit of calculation.
Check :  https://priyank-1.github.io/weather-react/
Bulit on the latest API response
