### ISSUE TITLE
problem with toast

### ISSUE THREAD

**Issue by Arpish00** [theyashpatel/yt-react-weather-app#3]
maybe there's problem with toast in react.development.js, they aren't loading instead causing whole page to go blank!

**Comment by Arpish00** [comment]
react.development.js:1626 
        
       Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at useReducer (react.development.js:1626:1)
    at useToastContainer (useToastContainer.ts:54:1)
    at ToastContainer.tsx:15:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)

**Comment by amansingh88688** [comment]
You just need to install toastify library:
**npm i react-toastify**
