### ISSUE TITLE
slice issue

### ISSUE THREAD

**Issue by Shikha0321** [theyashpatel/yt-react-weather-app#4]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slice')
    at formatForecastWeather (weatherService.js:48:1)
    at async getFormattedWeatherData (weatherService.js:75:1)
    at async fetchWeather (App.js:23:1)

**Comment by Siddhesh1123** [comment]
same issue
if you know the solution please let me know

**Comment by ghost** [comment]
@Shikha0321 @Siddhesh1123 

I ran into the same issue.

The problem is that the Free API version no longer supports "daily" or "hourly", so the .slice function is reading undefined.

Solution: Remove Forecast components from App.jsx, and daily and hourly from weatherServices.js. This fixes the issue.

**Comment by Siddhesh1123** [comment]
Yes ,Thanks you. I already done it thanks anyway 👍

**Comment by Shashwat-pati** [comment]
@yang2674 
Can you please explain where to edit in  App.js and weatherServices.js ??
I am not getting it.
