### ISSUE TITLE
problem with slice !!!

### ISSUE THREAD

**Issue by aliTalkhabi** [theyashpatel/yt-react-weather-app#5]
how to fixed this error in new version of react
Cannot read properties of undefined (reading 'slice')
TypeError: Cannot read properties of undefined (reading 'slice')
    at formatForecastWeather (http://localhost:3000/main.b55405993da2f79b51d1.hot-update.js:994:17)
    at async getFormattedWeatherData (http://localhost:3000/main.b55405993da2f79b51d1.hot-update.js:1020:36)
    at async fetchWeather (http://localhost:3000/main.7829d388bf2b118fe5e8.hot-update.js:49:7)
exept remove any components??

**Comment by Shashwat-pati** [comment]
Even i am getting the same erorr in weatherService file.
Can anyone please help me out???
